changesetIgnorePatterns:
  - "**/docs/**"

packageExtensions:
  "@jest/core@28.1.3":
    dependencies:
      ts-node: "*"
  "typeorm@0.3.7":
    peerDependencies:
      "mysql": "*"
  "local-pkg@0.4.2":
    peerDependencies:
      "@vitest/coverage-c8": "*"
      "jsdom": "*"
  "vitest@0.22.1":
    peerDependencies:
      "@vitest/coverage-c8": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
